### PR TITLE
Unnecessary host zone freezing

### LINKED ISSUE #111: Unnecessary Host Zone Freezing Due to Lack of Granular Error Handling
**Involved artifacts** 
• x/feeabs/ibc.go

**Description**
The system, as per the provided code snippets, exhibits a behavior where all host zones are attempted to be frozen in the event of an error acknowledgment received from inter-chain queries. The relevant logic is encapsulated in
the OnAcknowledgementPacket method and the helper method FrozenHostZoneByIBCDenom . Below is the code snippet from OnAcknowledgementPacket method where the system iterates over all host zones to
freeze them on encountering an error acknowledgment:
```
case *channeltypes.Acknowledgement_Error:
k.IterateHostZone(ctx, func(hostZoneConfig types.HostChainFeeAbsConfig) (stop
bool) {
err := k.FrozenHostZoneByIBCDenom(ctx, hostZoneConfig.IbcDenom) if err != nil {
              k.Logger(ctx).Error(fmt.Sprintf("Failed to frozen host zone %s",
  err.Error()))
}
return false
})
      k.Logger(ctx).Error(fmt.Sprintf("failed to send packet ICQ request %v",
  resp.Error))
```

**Problem Scenarios**
The current approach of freezing all host zones upon receiving an error acknowledgment can lead to a complete halt in system operations even if the error occurs to a single host zone. This approach lacks granularity and could significantly disrupt the user experience and system functionality.

### PR DESCRIPTION
**Pull request by minhngoc274**
Close #111

### CODE REVIEW

File: x/feeabs/keeper/ibc.go [hunk 1]
```diff
@@ -270,22 +271,38 @@ func (k Keeper) handleOsmosisIbcQuery(ctx sdk.Context) error {
...
 			params.NativeIbcedInOsmosis,
 			hostZoneConfig.OsmosisPoolTokenDenomIn,
 			startTime,
 		)
 		reqs = append(reqs, req)
+		batchCounter++
+		if batchCounter == batchSize {
+			err := k.SendOsmosisQueryRequest(ctx, reqs, types.IBCPortID, params.IbcQueryIcqChannel)
+			if err != nil {
+				return true
```
Comment (tnv1) [inline x/feeabs/keeper/ibc.go:292]: Add check if found error

**Review by tnv1 — APPROVED** [review]
